name: Render and deploy web site
on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/**"
            - "**.Rmd"
    pull_request:
        branches:
            - main
        paths:
            - ".github/workflows/**"
            - "**.Rmd"
    workflow_dispatch: # Allows manual execution of workflow

jobs:
    render-site:
        if: startsWith(github.ref, 'refs/pull/')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup R
              uses: r-lib/actions/setup-r@v2

            - name: Setup Pandoc
              uses: r-lib/actions/setup-pandoc@v2

            - name: Install the RMarkdown package
              run: Rscript -e 'install.packages("rmarkdown")'

            - name: Render web page
              run: Rscript -e 'rmarkdown::render("car-details-analysis-prediction.Rmd", output_format = "html_document")'

    render-and-deploy-site:
        if: startsWith(github.ref, 'refs/heads/')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup R
              uses: r-lib/actions/setup-r@v2

            - name: Setup Pandoc
              uses: r-lib/actions/setup-pandoc@v2

            - name: Install the RMarkdown package
              run: Rscript -e 'install.packages("rmarkdown")'

            - name: Render web page
              run: Rscript -e 'rmarkdown::render("car-details-analysis-prediction.Rmd", output_format = "html_document")'

            - name: Handle HTML file for deployment
              run: |
                  mv *.html index.html
                  mkdir build
                  mv index.html build

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4.2.5
              with:
                  branch: gh-pages
                  folder: build
                  clean: true
